apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-cinder-high-speed

